### ISSUE TITLE
templates in subdirectories not loaded via ATP, forward slashes stripped in request

### ISSUE THREAD

**Issue by richardtape** [Giuseppe-Mazzapica/ATP#2]
Hi Giuseppe,

Firstly, thanks so much for this, it is *awesome*.

I've come across a slight issue with regards to loading template files that are in sub directories. get_template_part() allows you to pass a path as the first argument. i.e.

```php
get_template_part( 'templates/tha_entry_top/entry', 'test' );
```

would load a file called `entry-test.php` in my theme's templates/tha_entry_top/ directory.

However, it appears that THA strips the forward slashes. I tried both

```php
ajax_template_part( 'templates/tha_entry_top/entry', 'test' );
```
and
```php
ajax_template_part( 'templates\/tha_entry_top\/entry', 'test' );
```

to see if I could manually unescape them, but both produced the following POST request form data;

```
action:ajaxtemplatepart
files_data[ajaxtemplate-templatestha_entry_topentry-test-1][]:templatestha_entry_topentry
files_data[ajaxtemplate-templatestha_entry_topentry-test-1][]:test
posts_data[ajaxtemplate-templatestha_entry_topentry-test-1]:1
```

Which, naturally, leads to the template not loading.

I'm a bit of a sucker for having a clean theme root directory, so I'd absolutely love ATP to allow templates to be loaded from sub directories. Again, thanks so much for writing this. It. Is. Awesome.

**Comment by Giuseppe-Mazzapica** [comment]
Thanks @richardtape

Yep, plugin should definitely support templates in subfolders. I'll surely handle this issue in the weekend. Thanks for reporting.

**Comment by richardtape** [comment]
Amazing. Thanks, @Giuseppe-Mazzapica

**Comment by Giuseppe-Mazzapica** [comment]
@richardtape Found few minutes to solve the issue. Now it works with subfolders.

**Comment by richardtape** [comment]
Thanks so much for working on this @Giuseppe-Mazzapica but sadly it doesn't seem to have quite worked.

```php
add_action( 'tha_entry_top', 'tha_entry_top__loadTestEntry' );
function tha_entry_top__loadTestEntry() {
	// ajax_template_part( 'entry', 'test' );
	ajax_template_part( 'templates/tha_entry_top/entry', 'test' );
	// get_template_part( 'templates/tha_entry_top/entry', 'test' );
}
```

Is my loader. If I use `ajax_template_part( 'entry', 'test' );` it works. If I use `get_template_part( 'templates/tha_entry_top/entry', 'test' );` However, if I use `ajax_template_part( 'templates/tha_entry_top/entry', 'test' );` it doesn't work. Here's the POST request and response;

```
action:ajaxtemplatepart
files_data%5Bajaxtemplate-templatestha_entry_topentry-test-1%5D%5B%5D:templatestha_entry_topentry
files_data%5Bajaxtemplate-templatestha_entry_topentry-test-1%5D%5B%5D:test
posts_data%5Bajaxtemplate-templatestha_entry_topentry-test-1%5D:1
```

```
{"success":true,"data":{"ajaxtemplate-templatestha_entry_topentry-test-1":""}}
```

The templates/tha_entry_top/entry-test.php file just contains plain text at the moment which says 'This is loaded via AJAX' so there's nothing in there that would be weird.

Maybe I'm doing something wrong? Let me know if you need any more info.

**Comment by Giuseppe-Mazzapica** [comment]
Have you updated via composer? If so, which is the version in your `composer.json`?

Can you confirm that [these 2 lines](https://github.com/Giuseppe-Mazzapica/ATP/blob/master/src/Templater.php#L25-27) in the file `src/Templater.php` appear like they are here on GitHub?

**Comment by richardtape** [comment]
I actually just created a new project in my downloads folder as per your instructions in the readme. (To try and prevent any problems).

In that same directory, I've also just run a `composer update` and received the following:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating optimized autoload files
Warning: Ambiguous class resolution, "Stash\Session\SessionHandlerInterface" was found in both "/Users/richardtape/Downloads/ajax-template-part/vendor/tedivm/stash/src/Stash/Session/SessionHandlerInterface_Legacy.php" and "/Users/richardtape/Downloads/ajax-template-part/vendor/tedivm/stash/src/Stash/Session/SessionHandlerInterface_Modern.php", the first will be used.
```

Finally, to answer your question, no, I do not see those lines in `src/Templater.php` like they are on github.

However, if I download the zip from github and stick those files into the plugin (leaving the vendor directory which was installed via composer previously)... IT WORKS! Yay!

I guess it's just a composer update problem. Thanks so much @Giuseppe-Mazzapica

**Comment by Giuseppe-Mazzapica** [comment]
Glad it works. Yes, was a composer update problem.
In facts in the messages you posted it says "Nothing to install or update".

Next time you can force updated version by calling from plugins dir

    composer create-project gmazzap/ajax-template-part ./ajax-template-part 1.1.* --no-dev
